// GENERATED by tools/gen-entity.ps1 from tools/trades.json - don't edit by hand.
export const TRADES = {
    "maxOffers":  3,
    "tiers":  [
                  1,
                  2,
                  3,
                  4,
                  6,
                  8,
                  12,
                  16
              ],
    "normalTier":  8,
    "professions":  {
                        "lumberjack":  {
                                           "code":  "L",
                                           "profession":  1,
                                           "displayName":  "entity.iv.lumberjack",
                                           "sells":  [
                                                         {
                                                             "item":  "minecraft:oak_log",
                                                             "per":  8,
                                                             "price":  1
                                                         },
                                                         {
                                                             "item":  "minecraft:spruce_log",
                                                             "per":  8,
                                                             "price":  1
                                                         },
                                                         {
                                                             "item":  "minecraft:birch_log",
                                                             "per":  8,
                                                             "price":  1
                                                         },
                                                         {
                                                             "item":  "minecraft:jungle_log",
                                                             "per":  8,
                                                             "price":  1
                                                         },
                                                         {
                                                             "item":  "minecraft:acacia_log",
                                                             "per":  8,
                                                             "price":  1
                                                         },
                                                         {
                                                             "item":  "minecraft:dark_oak_log",
                                                             "per":  8,
                                                             "price":  1
                                                         },
                                                         {
                                                             "item":  "minecraft:mangrove_log",
                                                             "per":  8,
                                                             "price":  1
                                                         },
                                                         {
                                                             "item":  "minecraft:cherry_log",
                                                             "per":  6,
                                                             "price":  1
                                                         },
                                                         {
                                                             "item":  "minecraft:pale_oak_log",
                                                             "per":  6,
                                                             "price":  1
                                                         },
                                                         {
                                                             "item":  "minecraft:poplar_log",
                                                             "per":  8,
                                                             "price":  1
                                                         }
                                                     ]
                                       },
                        "miner":  {
                                      "code":  "M",
                                      "profession":  2,
                                      "displayName":  "entity.iv.miner",
                                      "sells":  [
                                                    {
                                                        "item":  "minecraft:cobblestone",
                                                        "per":  16,
                                                        "price":  1
                                                    },
                                                    {
                                                        "item":  "minecraft:cobbled_deepslate",
                                                        "per":  16,
                                                        "price":  1
                                                    },
                                                    {
                                                        "item":  "minecraft:coal",
                                                        "per":  8,
                                                        "price":  1
                                                    },
                                                    {
                                                        "item":  "minecraft:raw_copper",
                                                        "per":  6,
                                                        "price":  1
                                                    },
                                                    {
                                                        "item":  "minecraft:raw_iron",
                                                        "per":  3,
                                                        "price":  1
                                                    },
                                                    {
                                                        "item":  "minecraft:raw_gold",
                                                        "per":  2,
                                                        "price":  1
                                                    }
                                                ]
                                  },
                        "farmer":  {
                                       "code":  "F",
                                       "profession":  3,
                                       "displayName":  "entity.iv.farmer",
                                       "sells":  [
                                                     {
                                                         "item":  "minecraft:wheat",
                                                         "per":  16,
                                                         "price":  1
                                                     },
                                                     {
                                                         "item":  "minecraft:carrot",
                                                         "per":  16,
                                                         "price":  1
                                                     },
                                                     {
                                                         "item":  "minecraft:potato",
                                                         "per":  16,
                                                         "price":  1
                                                     },
                                                     {
                                                         "item":  "minecraft:beetroot",
                                                         "per":  12,
                                                         "price":  1
                                                     },
                                                     {
                                                         "item":  "minecraft:bread",
                                                         "per":  5,
                                                         "price":  1
                                                     },
                                                     {
                                                         "item":  "minecraft:wheat_seeds",
                                                         "per":  24,
                                                         "price":  1
                                                     }
                                                 ]
                                   }
                    }
};
