// items.js - every item the shop sells.
// Prices are what a player pays to BUY one item. The sell price is worked out
// automatically from the "sell percent" chosen in the pack settings.
//
// Normal items: { name, id, cost, icon }
// Potions:      { name, id: "potion", data, cost, icon }   (data = potion type)
// Books:        { name, enchant, level, cost, icon }

// ---- OresAndRares ----
export const OresAndRaresType = [
  { name: "Clay", id: "clay_ball", cost: 30, icon: "textures/items/clay_ball" },
  { name: "Flint", id: "flint", cost: 10, icon: "textures/items/flint" },
  { name: "Quartz", id: "quartz", cost: 190, icon: "textures/items/quartz" },
  { name: "Coal", id: "coal", cost: 90, icon: "textures/items/coal" },
  { name: "Amethyst Shard", id: "amethyst_shard", cost: 90, icon: "textures/items/amethyst_shard" },
  { name: "Lapis", id: "lapis_lazuli", cost: 130, icon: "textures/items/dye_powder_blue" },
  { name: "Redstone", id: "redstone", cost: 30, icon: "textures/items/redstone_dust" },
  { name: "Copper", id: "copper_ingot", cost: 130, icon: "textures/items/copper_ingot" },
  { name: "Gold", id: "gold_ingot", cost: 590, icon: "textures/items/gold_ingot" },
  { name: "Iron", id: "iron_ingot", cost: 180, icon: "textures/items/iron_ingot" },
  { name: "Emerald", id: "emerald", cost: 550, icon: "textures/items/emerald" },
  { name: "Diamond", id: "diamond", cost: 5500, icon: "textures/items/diamond" },
  { name: "Netherite", id: "netherite_ingot", cost: 41510, icon: "textures/items/netherite_ingot" },
  { name: "Echo Shard", id: "echo_shard", cost: 920, icon: "textures/items/echo_shard" },
  { name: "Sculk Sensor", id: "sculk_sensor", cost: 880, icon: "textures/blocks/sculk_sensor_side" },
  { name: "Nether Star", id: "nether_star", cost: 300000, icon: "textures/items/nether_star" },
  { name: "Obsidian", id: "obsidian", cost: 1300, icon: "textures/blocks/obsidian" },
  { name: "Crying Obsidian", id: "crying_obsidian", cost: 3920, icon: "textures/blocks/crying_obsidian" },
  { name: "Experience Bottle", id: "experience_bottle", cost: 100, icon: "textures/items/experience_bottle" },
]

// ---- Utilities ----
export const UtilitiesType = [
  { name: "Snowball", id: "snowball", cost: 10, icon: "textures/items/snowball" },
  { name: "Saddle", id: "saddle", cost: 1100, icon: "textures/items/saddle" },
  { name: "Trident", id: "trident", cost: 790, icon: "textures/items/trident" },
  { name: "Elytra", id: "elytra", cost: 60000, icon: "textures/items/elytra" },
  { name: "Netherite Template", id: "netherite_upgrade_smithing_template", cost: 15000, icon: "textures/items/netherite_upgrade_smithing_template" },
  { name: "Milk Bucket", id: "milk_bucket", cost: 610, icon: "textures/items/bucket_milk" },
  { name: "Water Bucket", id: "water_bucket", cost: 610, icon: "textures/items/bucket_water" },
  { name: "Lava Bucket", id: "lava_bucket", cost: 620, icon: "textures/items/bucket_lava" },
  { name: "Cod Bucket", id: "cod_bucket", cost: 670, icon: "textures/items/bucket_cod" },
  { name: "Salmon Bucket", id: "salmon_bucket", cost: 670, icon: "textures/items/bucket_salmon" },
  { name: "Tropical Bucket", id: "tropical_fish_bucket", cost: 670, icon: "textures/items/bucket_tropical" },
  { name: "Pufferfish Bucket", id: "pufferfish_bucket", cost: 670, icon: "textures/items/bucket_pufferfish" },
  { name: "Powdered Snow Bucket", id: "powder_snow_bucket", cost: 630, icon: "textures/items/bucket_powder_snow" },
  { name: "Tadpole Bucket", id: "tadpole_bucket", cost: 550, icon: "textures/items/bucket_tadpole" },
  { name: "Axolotl Bucket", id: "axolotl_bucket", cost: 670, icon: "textures/items/bucket_axolotl" },
]

// ---- MobDrops ----
export const MobDropsType = [
  { name: "Rotten Flesh", id: "rotten_flesh", cost: 10, icon: "textures/items/rotten_flesh" },
  { name: "Bone", id: "bone", cost: 20, icon: "textures/items/bone" },
  { name: "Spider Eye", id: "spider_eye", cost: 30, icon: "textures/items/spider_eye" },
  { name: "Leather", id: "leather", cost: 50, icon: "textures/items/leather" },
  { name: "Rabbit Hide", id: "rabbit_hide", cost: 10, icon: "textures/items/rabbit_hide" },
  { name: "Rabbit Foot", id: "rabbit_foot", cost: 220, icon: "textures/items/rabbit_foot" },
  { name: "String", id: "string", cost: 20, icon: "textures/items/string" },
  { name: "Feather", id: "feather", cost: 10, icon: "textures/items/feather" },
  { name: "Gunpowder", id: "gunpowder", cost: 110, icon: "textures/items/gunpowder" },
  { name: "Glowstone Dust", id: "glowstone_dust", cost: 90, icon: "textures/items/glowstone_dust" },
  { name: "Egg", id: "egg", cost: 10, icon: "textures/items/egg" },
  { name: "Slimeball", id: "slime_ball", cost: 110, icon: "textures/items/slimeball" },
  { name: "Scute", id: "turtle_scute", cost: 10, icon: "textures/items/turtle_shell_piece" },
  { name: "Ender Pearl", id: "ender_pearl", cost: 550, icon: "textures/items/ender_pearl" },
  { name: "Phantom Membrane", id: "phantom_membrane", cost: 10, icon: "textures/items/phantom_membrane" },
  { name: "Ink Sac", id: "ink_sac", cost: 30, icon: "textures/items/dye_powder_black" },
  { name: "Glowing Ink Sac", id: "glow_ink_sac", cost: 30, icon: "textures/items/dye_powder_glow" },
  { name: "Ghast Tear", id: "ghast_tear", cost: 830, icon: "textures/items/ghast_tear" },
  { name: "Shulker Shell", id: "shulker_shell", cost: 340, icon: "textures/items/shulker_shell" },
  { name: "Blaze Rod", id: "blaze_rod", cost: 1100, icon: "textures/items/blaze_rod" },
  { name: "Wither Skeleton Skull", id: "wither_skeleton_skull", cost: 100000, icon: "textures/blocks/soul_sand" },
  { name: "Heart Of The Sea", id: "heart_of_the_sea", cost: 440, icon: "textures/items/heartofthesea_closed" },
  { name: "Nautilus Shell", id: "nautilus_shell", cost: 70, icon: "textures/items/nautilus" },
  { name: "Prismarine Crystals", id: "prismarine_crystals", cost: 830, icon: "textures/items/prismarine_crystals" },
  { name: "Prismarine Shard", id: "prismarine_shard", cost: 550, icon: "textures/items/prismarine_shard" },
  { name: "Totem", id: "totem_of_undying", cost: 3200, icon: "textures/items/totem" },
]

// ---- FoodsAndGrowables ----
export const FoodsAndGrowablesType = [
  { name: "Cod", id: "cod", cost: 30, icon: "textures/items/fish_raw" },
  { name: "Salmon", id: "salmon", cost: 40, icon: "textures/items/fish_salmon_raw" },
  { name: "Tropical Fish", id: "tropical_fish", cost: 120, icon: "textures/items/fish_clownfish_raw" },
  { name: "Pufferfish", id: "pufferfish", cost: 550, icon: "textures/items/fish_pufferfish_raw" },
  { name: "Raw Rabbit", id: "rabbit", cost: 20, icon: "textures/items/rabbit_raw" },
  { name: "Raw Mutton", id: "mutton", cost: 10, icon: "textures/items/mutton_raw" },
  { name: "Raw Porkchop", id: "porkchop", cost: 40, icon: "textures/items/porkchop_raw" },
  { name: "Raw Chicken", id: "chicken", cost: 30, icon: "textures/items/chicken_raw" },
  { name: "Raw Beef", id: "beef", cost: 60, icon: "textures/items/beef_raw" },
  { name: "Potato", id: "potato", cost: 10, icon: "textures/items/potato" },
  { name: "Carrot", id: "carrot", cost: 10, icon: "textures/items/carrot" },
  { name: "Apple", id: "apple", cost: 30, icon: "textures/items/apple" },
  { name: "Enchanted Apple", id: "enchanted_golden_apple", cost: 46000, icon: "textures/items/apple_golden" },
  { name: "Sweet Berries", id: "sweet_berries", cost: 30, icon: "textures/items/sweet_berries" },
  { name: "Glow Berries", id: "glow_berries", cost: 30, icon: "textures/items/glow_berries" },
  { name: "Torchflower Seeds", id: "torchflower_seeds", cost: 90, icon: "textures/items/torchflower_seeds" },
  { name: "Chorus Flower", id: "chorus_flower", cost: 275, icon: "textures/blocks/chorus_flower" },
  { name: "Chorus Fruit", id: "chorus_fruit", cost: 60, icon: "textures/items/chorus_fruit" },
  { name: "Red Mushroom", id: "red_mushroom", cost: 10, icon: "textures/blocks/mushroom_red" },
  { name: "Brown Mushroom", id: "brown_mushroom", cost: 10, icon: "textures/blocks/mushroom_brown" },
  { name: "Warped Fungus", id: "warped_fungus", cost: 10, icon: "textures/blocks/warped_fungus" },
  { name: "Crimson Fungus", id: "crimson_fungus", cost: 10, icon: "textures/blocks/crimson_fungus" },
  { name: "Kelp", id: "kelp", cost: 30, icon: "textures/items/kelp" },
  { name: "Sugar Cane", id: "sugar_cane", cost: 10, icon: "textures/items/reeds" },
  { name: "Bamboo", id: "bamboo", cost: 10, icon: "textures/items/bamboo" },
  { name: "Cactus", id: "cactus", cost: 60, icon: "textures/blocks/cactus_top" },
  { name: "Nether Wart", id: "nether_wart", cost: 170, icon: "textures/items/nether_wart" },
  { name: "Seeds", id: "wheat_seeds", cost: 10, icon: "textures/items/seeds_wheat" },
  { name: "Pumpkin Seeds", id: "pumpkin_seeds", cost: 50, icon: "textures/items/seeds_pumpkin" },
  { name: "Melon Seeds", id: "melon_seeds", cost: 50, icon: "textures/items/seeds_melon" },
  { name: "Beetroot Seeds", id: "beetroot_seeds", cost: 10, icon: "textures/items/seeds_beetroot" },
  { name: "Cocoa Seeds", id: "cocoa_beans", cost: 50, icon: "textures/items/dye_powder_brown" },
  { name: "Pointed Dripstone", id: "pointed_dripstone", cost: 10, icon: "textures/blocks/pointed_dripstone_down_tip" },
  { name: "Bone Meal", id: "bone_meal", cost: 10, icon: "textures/items/dye_powder_white" },
]

// ---- Potions ----
export const PotionsType = [
  { name: "Night Vision 8min", id: "potion", data: 6, cost: 900, icon: "textures/items/potion_bottle_nightVision" },
  { name: "Invisibility 8min", id: "potion", data: 8, cost: 1150, icon: "textures/items/potion_bottle_invisibility" },
  { name: "Jump Boost 8min", id: "potion", data: 10, cost: 900, icon: "textures/items/potion_bottle_jump" },
  { name: "Fire Resistance 8min", id: "potion", data: 13, cost: 510, icon: "textures/items/potion_bottle_fireResistance" },
  { name: "Speed Boost 8min", id: "potion", data: 15, cost: 900, icon: "textures/items/potion_bottle_moveSpeed" },
  { name: "Slowness 8min", id: "potion", data: 18, cost: 900, icon: "textures/items/potion_bottle_moveSpeed" },
  { name: "Water Breathing 8min", id: "potion", data: 20, cost: 300, icon: "textures/items/potion_bottle_waterBreathing" },
  { name: "Instant Health 2", id: "potion", data: 22, cost: 900, icon: "textures/items/potion_bottle_waterBreathing" },
  { name: "Regeneration 1.5min", id: "potion", data: 29, cost: 900, icon: "textures/items/potion_bottle_regeneration" },
  { name: "Strength 8min", id: "potion", data: 32, cost: 900, icon: "textures/items/potion_bottle_resistance" },
  { name: "Weakness 8min", id: "potion", data: 35, cost: 110, icon: "textures/items/potion_bottle_weakness" },
  { name: "Slow Falling", id: "potion", data: 41, cost: 590, icon: "textures/items/potion_bottle_slowFall" },
  { name: "XP Bottle", id: "experience_bottle", cost: 100, icon: "textures/items/experience_bottle" },
]

// ---- Books ----
export const BooksType = [
  { name: "Aqua Affinity I", enchant: "aqua_affinity", level: 1, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Bane Of Arthropods V", enchant: "bane_of_arthropods", level: 5, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Blast Protection IV", enchant: "blast_protection", level: 4, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Breach IV", enchant: "breach", level: 4, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Channeling I", enchant: "channeling", level: 1, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Curse of Binding I", enchant: "binding", level: 1, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Curse of Vanishing I", enchant: "vanishing", level: 1, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Density V", enchant: "density", level: 5, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Depth Strider III", enchant: "depth_strider", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Efficiency III", enchant: "efficiency", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Efficiency V", enchant: "efficiency", level: 5, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Feather Falling IV", enchant: "feather_falling", level: 4, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Fire Aspect II", enchant: "fire_aspect", level: 2, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Fire Protection IV", enchant: "fire_protection", level: 4, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Flame I", enchant: "flame", level: 1, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Fortune III", enchant: "fortune", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Frost Walker II", enchant: "frost_walker", level: 2, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Impaling V", enchant: "impaling", level: 5, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Infinity I", enchant: "infinity", level: 1, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Knockback II", enchant: "knockback", level: 2, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Looting III", enchant: "looting", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Lure III", enchant: "lure", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Loyalty III", enchant: "loyalty", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Luck of the Sea III", enchant: "luck_of_the_sea", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Mending I", enchant: "mending", level: 1, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Multishot I", enchant: "multishot", level: 1, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Piercing III", enchant: "piercing", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Power V", enchant: "power", level: 5, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Projectile Protection IV", enchant: "projectile_protection", level: 4, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Protection IV", enchant: "protection", level: 4, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Punch II", enchant: "punch", level: 2, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Quick Charge III", enchant: "quick_charge", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Respiration III", enchant: "respiration", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Riptide III", enchant: "riptide", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Sharpness V", enchant: "sharpness", level: 5, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Silk Touch I", enchant: "silk_touch", level: 1, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Smite V", enchant: "smite", level: 5, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Soul Speed III", enchant: "soul_speed", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Swift Sneak III", enchant: "swift_sneak", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Thorns III", enchant: "thorns", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Unbreaking III", enchant: "unbreaking", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
  { name: "Wind Burst III", enchant: "wind_burst", level: 3, cost: 900, icon: "textures/items/book_enchanted" },
]

// ---- TreesAndGrass ----
export const TreesAndGrassType = [
  { name: "Oak Log", id: "oak_log", cost: 110, icon: "textures/blocks/log_oak" },
  { name: "Spruce Log", id: "spruce_log", cost: 110, icon: "textures/blocks/log_spruce" },
  { name: "Birch Log", id: "birch_log", cost: 110, icon: "textures/blocks/log_birch" },
  { name: "Jungle Log", id: "jungle_log", cost: 110, icon: "textures/blocks/log_jungle" },
  { name: "Acacia Log", id: "acacia_log", cost: 110, icon: "textures/blocks/log_acacia" },
  { name: "Dark Oak Log", id: "dark_oak_log", cost: 110, icon: "textures/blocks/log_big_oak" },
  { name: "Mangrove Log", id: "mangrove_log", cost: 110, icon: "textures/blocks/mangrove_log_side" },
  { name: "Cherry Log", id: "cherry_log", cost: 220, icon: "textures/blocks/cherry_log_side" },
  { name: "Pale Oak Log", id: "pale_oak_log", cost: 220, icon: "textures/blocks/pale_oak_log_side" },
  { name: "Crimson Stem", id: "crimson_stem", cost: 130, icon: "textures/blocks/huge_fungus/crimson_log_top" },
  { name: "Warped Stem", id: "warped_stem", cost: 130, icon: "textures/blocks/huge_fungus/warped_stem_top" },
  { name: "Oak Leaves", id: "oak_leaves", cost: 20, icon: "textures/blocks/azalea_leaves" },
  { name: "Spruce Leaves", id: "spruce_leaves", cost: 20, icon: "textures/blocks/azalea_leaves" },
  { name: "Birch Leaves", id: "birch_leaves", cost: 20, icon: "textures/blocks/azalea_leaves" },
  { name: "Jungle Leaves", id: "jungle_leaves", cost: 20, icon: "textures/blocks/azalea_leaves" },
  { name: "Acacia Leaves", id: "acacia_leaves", cost: 20, icon: "textures/blocks/azalea_leaves" },
  { name: "Dark Oak Leaves", id: "dark_oak_leaves", cost: 20, icon: "textures/blocks/azalea_leaves" },
  { name: "Mangrove Leaves", id: "mangrove_leaves", cost: 20, icon: "textures/blocks/azalea_leaves" },
  { name: "Cherry Leaves", id: "cherry_leaves", cost: 40, icon: "textures/blocks/cherry_leaves" },
  { name: "Pale Oak Leaves", id: "pale_oak_leaves", cost: 40, icon: "textures/blocks/pale_oak_leaves" },
  { name: "Azalea Leaves", id: "azalea_leaves", cost: 20, icon: "textures/blocks/azalea_leaves" },
  { name: "Flowering Azalea Leaves", id: "azalea_leaves_flowered", cost: 30, icon: "textures/blocks/azalea_leaves_flowers" },
  { name: "Oak Sapling", id: "oak_sapling", cost: 20, icon: "textures/blocks/sapling_oak" },
  { name: "Spruce Sapling", id: "spruce_sapling", cost: 20, icon: "textures/blocks/sapling_spruce" },
  { name: "Birch Sapling", id: "birch_sapling", cost: 20, icon: "textures/blocks/sapling_birch" },
  { name: "Jungle Sapling", id: "jungle_sapling", cost: 20, icon: "textures/blocks/sapling_jungle" },
  { name: "Acacia Sapling", id: "acacia_sapling", cost: 20, icon: "textures/blocks/sapling_acacia" },
  { name: "Dark Oak Sapling", id: "dark_oak_sapling", cost: 20, icon: "textures/blocks/sapling_roofed_oak" },
  { name: "Mangrove Propagule", id: "mangrove_propagule", cost: 20, icon: "textures/items/mangrove_propagule" },
  { name: "Cherry Sapling", id: "cherry_sapling", cost: 40, icon: "textures/blocks/cherry_sapling" },
  { name: "Pale Oak Sapling", id: "pale_oak_sapling", cost: 40, icon: "textures/blocks/pale_oak_sapling" },
  { name: "Tall Grass", id: "tall_grass", cost: 2, icon: "textures/blocks/double_plant_grass_carried" },
  { name: "Short Grass", id: "short_grass", cost: 2, icon: "textures/blocks/tallgrass_carried" },
  { name: "Nether Sprout", id: "nether_sprouts", cost: 2, icon: "textures/blocks/nether_sprouts" },
  { name: "Weeping Vines", id: "weeping_vines", cost: 2, icon: "textures/blocks/weeping_vines_base" },
  { name: "Vines", id: "vine", cost: 2, icon: "textures/blocks/vine_carried" },
  { name: "Twisting Vines", id: "twisting_vines", cost: 2, icon: "textures/blocks/twisting_vines_base" },
  { name: "Lily Pad", id: "waterlily", cost: 10, icon: "textures/blocks/carried_waterlily" },
  { name: "Sea Grass", id: "seagrass", cost: 10, icon: "textures/blocks/seagrass_carried" },
  { name: "Moss Block", id: "moss_block", cost: 30, icon: "textures/blocks/moss_block" },
  { name: "Big Dripleaf", id: "big_dripleaf", cost: 60, icon: "textures/blocks/big_dripleaf_top" },
  { name: "Small Dripleaf", id: "small_dripleaf_block", cost: 60, icon: "textures/blocks/small_dripleaf_top" },
]

// ---- FlowersAndDyes ----
export const FlowersAndDyesType = [
  { name: "Poppy", id: "poppy", cost: 10, icon: "textures/blocks/flower_rose" },
  { name: "Blue Orchid", id: "blue_orchid", cost: 10, icon: "textures/blocks/flower_blue_orchid" },
  { name: "Allium", id: "allium", cost: 60, icon: "textures/blocks/flower_allium" },
  { name: "Azure Bluet", id: "azure_bluet", cost: 20, icon: "textures/blocks/flower_houstonia" },
  { name: "Red Tulip", id: "red_tulip", cost: 20, icon: "textures/blocks/flower_tulip_red" },
  { name: "Orange Tulip", id: "orange_tulip", cost: 20, icon: "textures/blocks/flower_tulip_orange" },
  { name: "White Tulip", id: "white_tulip", cost: 20, icon: "textures/blocks/flower_tulip_white" },
  { name: "Pink Tulip", id: "pink_tulip", cost: 20, icon: "textures/blocks/flower_tulip_pink" },
  { name: "Oxeye Daisy", id: "oxeye_daisy", cost: 20, icon: "textures/blocks/flower_oxeye_daisy" },
  { name: "Cornflower", id: "cornflower", cost: 30, icon: "textures/blocks/flower_cornflower" },
  { name: "Lily Of The Valley", id: "lily_of_the_valley", cost: 30, icon: "textures/blocks/flower_lily_of_the_valley" },
  { name: "Dandelion", id: "dandelion", cost: 10, icon: "textures/blocks/flower_dandelion" },
  { name: "Sunflower", id: "sunflower", cost: 30, icon: "textures/blocks/double_plant_sunflower_front" },
  { name: "Lilac", id: "lilac", cost: 30, icon: "textures/blocks/double_plant_paeonia_bottom" },
  { name: "Rose Bush", id: "rose_bush", cost: 10, icon: "textures/blocks/double_plant_rose_top" },
  { name: "Peony", id: "peony", cost: 10, icon: "textures/blocks/double_plant_paeonia_top" },
  { name: "Pitcher Plant", id: "pitcher_plant", cost: 60, icon: "textures/blocks/pitcher_crop_top_stage_4" },
  { name: "Pink Petals", id: "pink_petals", cost: 10, icon: "textures/items/pink_petals" },
  { name: "Wither Rose", id: "wither_rose", cost: 2250, icon: "textures/blocks/flower_wither_rose" },
  { name: "Torchflower", id: "torchflower", cost: 60, icon: "textures/blocks/torchflower" },
  { name: "Crimson Roots", id: "crimson_roots", cost: 1, icon: "textures/blocks/crimson_roots" },
  { name: "Warped Roots", id: "warped_roots", cost: 1, icon: "textures/blocks/warped_roots" },
  { name: "White Dye", id: "white_dye", cost: 10, icon: "textures/items/dye_powder_white_new" },
  { name: "Light Gray Dye", id: "light_gray_dye", cost: 10, icon: "textures/items/dye_powder_silver" },
  { name: "Gray Dye", id: "gray_dye", cost: 10, icon: "textures/items/dye_powder_gray" },
  { name: "Black Dye", id: "black_dye", cost: 30, icon: "textures/items/dye_powder_black_new" },
  { name: "Brown Dye", id: "brown_dye", cost: 60, icon: "textures/items/dye_powder_brown_new" },
  { name: "Red Dye", id: "red_dye", cost: 60, icon: "textures/items/dye_powder_red" },
  { name: "Orange Dye", id: "orange_dye", cost: 10, icon: "textures/items/dye_powder_orange" },
  { name: "Yellow Dye", id: "yellow_dye", cost: 10, icon: "textures/items/dye_powder_yellow" },
  { name: "Lime Dye", id: "lime_dye", cost: 40, icon: "textures/items/dye_powder_lime" },
  { name: "Green Dye", id: "green_dye", cost: 70, icon: "textures/items/dye_powder_green" },
  { name: "Cyan Dye", id: "cyan_dye", cost: 50, icon: "textures/items/dye_powder_cyan" },
  { name: "Light Blue Dye", id: "light_blue_dye", cost: 20, icon: "textures/items/dye_powder_light_blue" },
  { name: "Blue Dye", id: "blue_dye", cost: 30, icon: "textures/items/dye_powder_blue_new" },
  { name: "Purple Dye", id: "purple_dye", cost: 20, icon: "textures/items/dye_powder_purple" },
  { name: "Magenta Dye", id: "magenta_dye", cost: 10, icon: "textures/items/dye_powder_magenta" },
  { name: "Pink Dye", id: "pink_dye", cost: 10, icon: "textures/items/dye_powder_pink" },
]

// ---- Concrete ----
export const ConcreteType = [
  { name: "White Concrete", id: "white_concrete", cost: 10, icon: "textures/blocks/concrete_white" },
  { name: "Light Gray Concrete", id: "light_gray_concrete", cost: 10, icon: "textures/blocks/concrete_silver" },
  { name: "Gray Concrete", id: "gray_concrete", cost: 10, icon: "textures/blocks/concrete_gray" },
  { name: "Black Concrete", id: "black_concrete", cost: 10, icon: "textures/blocks/concrete_black" },
  { name: "Brown Concrete", id: "brown_concrete", cost: 10, icon: "textures/blocks/concrete_brown" },
  { name: "Red Concrete", id: "red_concrete", cost: 10, icon: "textures/blocks/concrete_red" },
  { name: "Orange Concrete", id: "orange_concrete", cost: 10, icon: "textures/blocks/concrete_orange" },
  { name: "Yellow Concrete", id: "yellow_concrete", cost: 10, icon: "textures/blocks/concrete_yellow" },
  { name: "Lime Concrete", id: "lime_concrete", cost: 10, icon: "textures/blocks/concrete_lime" },
  { name: "Green Concrete", id: "green_concrete", cost: 10, icon: "textures/blocks/concrete_green" },
  { name: "Cyan Concrete", id: "cyan_concrete", cost: 10, icon: "textures/blocks/concrete_cyan" },
  { name: "Light Blue Concrete", id: "light_blue_concrete", cost: 10, icon: "textures/blocks/concrete_light_blue" },
  { name: "Blue Concrete", id: "blue_concrete", cost: 10, icon: "textures/blocks/concrete_blue" },
  { name: "Purple Concrete", id: "purple_concrete", cost: 10, icon: "textures/blocks/concrete_purple" },
  { name: "Magenta Concrete", id: "magenta_concrete", cost: 10, icon: "textures/blocks/concrete_magenta" },
  { name: "Pink Concrete", id: "pink_concrete", cost: 10, icon: "textures/blocks/concrete_pink" },
]

// ---- GeneralBlocks ----
export const GeneralBlocksType = [
  { name: "Sand", id: "sand", cost: 10, icon: "textures/blocks/sand" },
  { name: "Red Sand", id: "red_sand", cost: 20, icon: "textures/blocks/red_sand" },
  { name: "Gravel", id: "gravel", cost: 10, icon: "textures/blocks/gravel" },
  { name: "Soul Sand", id: "soul_sand", cost: 110, icon: "textures/blocks/soul_sand" },
  { name: "Soul Soil", id: "soul_soil", cost: 110, icon: "textures/blocks/soul_soil" },
  { name: "Dirt", id: "dirt", cost: 10, icon: "textures/blocks/dirt" },
  { name: "Rooted Dirt", id: "dirt_with_roots", cost: 20, icon: "textures/blocks/dirt_with_roots" },
  { name: "Podzol", id: "podzol", cost: 30, icon: "textures/blocks/dirt_podzol_side" },
  { name: "Mycelium", id: "mycelium", cost: 110, icon: "textures/blocks/mycelium_side" },
  { name: "Mud", id: "mud", cost: 10, icon: "textures/blocks/mud" },
  { name: "Warped Wart Block", id: "warped_wart_block", cost: 170, icon: "textures/blocks/warped_wart_block" },
  { name: "Warped Nylium", id: "warped_nylium", cost: 20, icon: "textures/blocks/warped_nylium_side" },
  { name: "Crimson Nylium", id: "crimson_nylium", cost: 20, icon: "textures/blocks/crimson_nylium_side" },
  { name: "Netherrack", id: "netherrack", cost: 20, icon: "textures/blocks/netherrack" },
  { name: "Cobblestone", id: "cobblestone", cost: 10, icon: "textures/blocks/cobblestone" },
  { name: "Granite", id: "granite", cost: 10, icon: "textures/blocks/stone_granite" },
  { name: "Diorite", id: "diorite", cost: 10, icon: "textures/blocks/stone_diorite" },
  { name: "Andesite", id: "andesite", cost: 10, icon: "textures/blocks/stone_andesite" },
  { name: "Blackstone", id: "blackstone", cost: 20, icon: "textures/blocks/blackstone" },
  { name: "Cobbled Deepslate", id: "cobbled_deepslate", cost: 10, icon: "textures/blocks/deepslate/cobbled_deepslate" },
  { name: "Calcite", id: "calcite", cost: 10, icon: "textures/blocks/calcite" },
  { name: "Tuff", id: "tuff", cost: 10, icon: "textures/blocks/tuff" },
  { name: "Terracotta", id: "hardened_clay", cost: 160, icon: "textures/blocks/hardened_clay" },
  { name: "Budding Amethyst", id: "budding_amethyst", cost: 590, icon: "textures/blocks/budding_amethyst" },
  { name: "Dripstone Block", id: "dripstone_block", cost: 20, icon: "textures/blocks/dripstone_block" },
  { name: "Endstone", id: "end_stone", cost: 110, icon: "textures/blocks/end_stone" },
  { name: "Sponge", id: "sponge", cost: 120, icon: "textures/blocks/sponge" },
  { name: "Shroomlight", id: "shroomlight", cost: 440, icon: "textures/blocks/shroomlight" },
  { name: "Pearlescent Froglight", id: "pearlescent_froglight", cost: 590, icon: "textures/blocks/pearlescent_froglight_side" },
  { name: "Ochre Froglight", id: "ochre_froglight", cost: 590, icon: "textures/blocks/ochre_froglight_side" },
  { name: "Verdant Froglight", id: "verdant_froglight", cost: 590, icon: "textures/blocks/verdant_froglight_side" },
  { name: "Glass", id: "glass", cost: 20, icon: "textures/blocks/glass" },
  { name: "Ice", id: "ice", cost: 80, icon: "textures/blocks/ice" },
]

// Main menu layout. Remove or reorder entries here to change the shop.
export const CATEGORIES = [
  { title: "Ores & Rare Items", icon: "textures/items/diamond", items: OresAndRaresType },
  { title: "Utilities", icon: "textures/items/elytra", items: UtilitiesType },
  { title: "Mob Drops", icon: "textures/items/ender_pearl", items: MobDropsType },
  { title: "Foods & Growables", icon: "textures/items/apple", items: FoodsAndGrowablesType },
  { title: "Potions", icon: "textures/items/potion_bottle_jump", items: PotionsType },
  { title: "Enchanted Books", icon: "textures/items/book_enchanted", items: BooksType, books: true },
  { title: "Trees & Grass", icon: "textures/blocks/sapling_oak", items: TreesAndGrassType },
  { title: "Flowers & Dyes", icon: "textures/blocks/flower_rose", items: FlowersAndDyesType },
  { title: "Concrete", icon: "textures/blocks/concrete_magenta", items: ConcreteType },
  { title: "General Blocks", icon: "textures/blocks/cobblestone", items: GeneralBlocksType },
]
