#!/usr/bin/env python3
"""Writes IndependentVillagers_BP/scripts/names_data.js: 1000 different villager names.

Half are ordinary first names, the rest are made-up village names put together from syllables.
The list is the same every time (a fixed random seed), so re-running it doesn't reshuffle anyone.

    python3 tools/gen_names.py
"""
import os
import random

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OUT = os.path.join(ROOT, "IndependentVillagers_BP", "scripts", "names_data.js")

REAL = """
Aaron Abel Ada Adele Agnes Alan Albert Alfie Alice Alma Amos Amy Andy Angus Anna Annie Arlo Arthur
Ava Barney Basil Bea Bella Ben Bernie Bert Beth Betty Bill Billy Blake Bob Bonnie Boris Brenda Brian
Bruno Bud Caleb Calvin Carl Carla Carol Cecil Celia Chad Charlie Chester Chloe Clara Clark Claude
Clive Colin Connie Cora Craig Cyril Daisy Dale Dan Daphne Darcy Dave Dean Della Dennis Derek Dexter
Diana Dolly Don Donna Dora Doris Dot Doug Duncan Dwight Earl Ed Edgar Edie Edith Edna Effie Elaine
Eli Eliza Ella Ellie Elmer Elsa Elsie Emil Emma Enid Eric Ernie Esther Ethan Ethel Eva Evan Ezra
Faye Felix Fern Fiona Flora Floyd Frank Fred Freya Gail Gary Gavin Gene George Gerald Gina Glen
Gloria Gordon Grace Greta Gus Gwen Hal Hank Hannah Harold Harriet Harry Hazel Heath Hector Heidi
Helen Henry Herb Hilda Holly Homer Howard Hugh Hugo Ian Ida Igor Imogen Ingrid Ira Iris Irma Isaac
Ivan Ivy Jack Jade Jake James Jan Jane Janet Jasper Jean Jed Jeff Jenny Jess Jill Jim Joan Joe
Joel John Jonah Josie Joy Jude Judy Jules June Karl Kate Keith Ken Kent Kirk Kit Lana Lance Lars
Laura Lee Lena Len Leo Leon Les Levi Lily Linda Lionel Lisa Liz Lloyd Lois Lola Lou Lucy Luke Lyle
Mabel Mack Madge Mae Maggie Marco Margo Maria Marge Mark Martha Marv Mary Matt Maud Max Mavis May
Mel Mia Mick Mike Miles Millie Milo Mina Minnie Miriam Mitch Molly Mona Morris Moss Myra Nan Nancy
Nat Ned Nell Nettie Nick Nina Noah Noel Nora Norm Olga Olive Oliver Ollie Omar Opal Oscar Otis Otto
Owen Pam Pat Paul Pearl Peg Penny Percy Pete Phil Phoebe Pip Polly Quinn Ralph Ray Reg Rex Rhoda
Rita Rob Rod Rolf Ron Rosa Rose Roy Ruby Rudy Rufus Russ Ruth Sal Sam Sandy Sara Saul Scott Seth
Shane Sid Silas Simon Stan Stella Sue Sven Sybil Ted Tess Thea Theo Tilly Tim Tina Toby Todd Tom
Tony Trudy Ula Una Val Vera Vic Viola Vince Violet Wade Wally Walt Wanda Warren Wendy Wes Will
Wilma Winnie Wyatt Yara Yvonne Zach Zara Zeke Zoe Abbot Aggie Alder Ansel Ardith Barnaby Bartholomew
Bram Brigid Cedric Clement Cuthbert Dorian Edmund Elric Ester Fenwick Gideon Godfrey Gwendolyn
Humphrey Ignatius Jethro Leopold Lorcan Magnus Marigold Mortimer Nigel Osric Oswald Percival
Quentin Reginald Rowena Sebastian Tobias Ulric Wilfred Winifred Agatha Alistair Beatrix Cornelius
Delphine Eamon Florian Gretchen Horace Isolde Jasmine Leander Lucius Matilda Nessa Octavia Philippa
Rosalind Sabine Thaddeus Ursula Vivian Wendel Xavier Yorick Zelda Ambrose Bertram Clover Dorcas
Elspeth Fitz Garrick Hettie Innes Jolyon Kester Lettice Merrick Nicolette Orla Perpetua Rupert
Tamsin Verity Wystan Abner Blythe Crispin Drusilla Evander Fenella Galen Hesper Ivo Jocasta Lavinia
Mungo Ninian Obadiah Prudence Roderick Seraphina Tristram Urban Wilhelmina Yves Barnabus Clem
Dunstan Ebenezer Hamish Hortense Josiah Lemuel Mercy Norbert Ophelia Piers Rafe Sigrid Tabitha
""".split()

STARTS = ["Al", "Bar", "Bel", "Bran", "Cal", "Cor", "Dar", "Del", "Dor", "El", "Fen", "Gar", "Gil", "Hal", "Har", "Hol", "Jor", "Kel", "Lor", "Mal",
          "Mar", "Mer", "Nor", "Ed", "Or", "Pel", "Quil", "Ran", "Ros", "Sel", "Tal", "Tam", "Tor", "Ul", "Val", "Wil", "Wyn", "Yor", "Ash", "Bri"]
ENDS = ["a", "an", "and", "as", "ben", "bert", "bin", "da", "den", "dric", "ella", "en", "ey", "fred", "ga", "gan", "ia", "ic", "in", "ina",
        "ion", "is", "ley", "lin", "lo", "ly", "mar", "mund", "na", "o", "on", "ora", "ric", "rin", "ris", "son", "ta", "tha", "win", "wyn"]


def main():
    seen = set()
    names = []
    for n in REAL:
        if n not in seen:
            seen.add(n)
            names.append(n)
    rng = random.Random(1000)
    made = [s + e for s in STARTS for e in ENDS]
    rng.shuffle(made)
    for n in made:
        if len(names) >= 1000:
            break
        # no doubled-up letters at the join (Allan is fine as a real name, "Mall" isn't a name)
        if n in seen or n[len(n) - 1] == n[len(n) - 2] == n[len(n) - 3]:
            continue
        seen.add(n)
        names.append(n)
    assert len(names) == 1000, len(names)
    rng.shuffle(names)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// GENERATED by tools/gen_names.py - 1000 villager names, don't edit by hand.\n")
        f.write("export const NAMES = [\n")
        for i in range(0, 1000, 12):
            f.write("  " + ", ".join(f'"{n}"' for n in names[i : i + 12]) + ",\n")
        f.write("];\n")
    print(f"{len(names)} names ({len([n for n in names if n in REAL])} real, the rest made up)")


if __name__ == "__main__":
    main()
