#!/usr/bin/env python3
"""Regenerates everything the trade screens need from tools/trades.json.

Vanilla trade screens read fixed JSON tables, so there is one table per combination of up to
`maxOffers` stocked items and per stock tier (trading/iv/<code>_<i>_<j>_t<tier>.json), a component
group + event on iv:villager for each table, and scripts/trades_data.js for trade.js to pick the
table that matches a villager's shop row.

    python3 tools/gen_trades.py

(Replaces tools/gen-entity.ps1 for the trade parts; the rest of the entity file is left as it is.)
"""
import json
import os
from itertools import combinations

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
BP = os.path.join(ROOT, "IndependentVillagers_BP")
ENTITY = os.path.join(BP, "entities", "iv_villager.json")
TRADING = os.path.join(BP, "trading", "iv")
DATA_JS = os.path.join(BP, "scripts", "trades_data.js")


def dumps(obj):
    return json.dumps(obj, separators=(",", ":"), ensure_ascii=False)


def combos(n, k_max):
    """Every set of 1..k_max sell indices, in the order the tables have always been listed in."""
    out = []

    def walk(start, cur):
        for i in range(start, n):
            nxt = cur + [i]
            out.append(nxt)
            if len(nxt) < k_max:
                walk(i + 1, nxt)

    walk(0, [])
    return out


def table(sells, listed, tier):
    trades = []
    for i in listed:
        s = sells[i]
        trades.append(
            {
                "wants": [{"quantity": s["price"], "item": "minecraft:emerald"}],
                "gives": [{"quantity": s["per"], "item": s["item"]}],
                "trader_exp": 1,
                "max_uses": tier,
                "reward_exp": True,
            }
        )
    return {"tiers": [{"total_exp_required": 0, "groups": [{"num_to_select": len(listed), "trades": trades}]}]}


def main():
    with open(os.path.join(ROOT, "tools", "trades.json"), encoding="utf-8") as f:
        cfg = json.load(f)
    tiers = cfg["tiers"]
    k_max = cfg["maxOffers"]

    keys = []  # (key, display name)
    os.makedirs(TRADING, exist_ok=True)
    wanted_files = set()
    for prof in cfg["professions"].values():
        sells = prof["sells"]
        for listed in combos(len(sells), k_max):
            for tier in tiers:
                key = f"{prof['code']}_{'_'.join(map(str, listed))}_t{tier}"
                name = f"{key}.json"
                wanted_files.add(name)
                path = os.path.join(TRADING, name)
                body = dumps(table(sells, listed, tier))
                old = None
                if os.path.exists(path):
                    with open(path, encoding="utf-8") as f:
                        old = f.read()
                if old != body:
                    with open(path, "w", encoding="utf-8", newline="") as f:
                        f.write(body)
                keys.append((key, prof["displayName"]))
    for name in os.listdir(TRADING):
        if name.endswith(".json") and name not in wanted_files:
            os.remove(os.path.join(TRADING, name))

    with open(ENTITY, encoding="utf-8") as f:
        ent = json.load(f)
    e = ent["minecraft:entity"]

    max_prof = max(p["profession"] for p in cfg["professions"].values())
    prop = e["description"]["properties"]["iv:profession"]
    prop["range"] = [0, max(prop["range"][1], max_prof)]

    def rebuild(section, make, tail):
        old = e[section]
        head = {k: v for k, v in old.items() if not k.startswith("iv:trade_") and k not in tail}
        rest = {k: old[k] for k in tail if k in old}
        new = dict(head)
        for key, name in keys:
            new[f"iv:trade_{key}"] = make(key, name)
        new.update(rest)
        e[section] = new

    rebuild(
        "component_groups",
        lambda key, name: {
            "minecraft:economy_trade_table": {
                "display_name": name,
                "table": f"trading/iv/{key}.json",
                "new_screen": True,
                "persist_trades": False,
                "use_legacy_price_formula": True,
            }
        },
        ["iv:resupply"],
    )
    e["events"].pop("iv:trade_clear", None)
    rebuild("events", lambda key, name: {"add": {"component_groups": [f"iv:trade_{key}"]}}, ["iv:resupply", "iv:resupply_done"])
    # trade_clear goes right before the resupply events, like it always has
    events = {}
    for k, v in e["events"].items():
        if k == "iv:resupply":
            events["iv:trade_clear"] = {"remove": {"component_groups": [f"iv:trade_{key}" for key, _ in keys]}}
        events[k] = v
    e["events"] = events

    with open(ENTITY, "w", encoding="utf-8", newline="") as f:
        f.write(dumps(ent))

    with open(DATA_JS, "w", encoding="utf-8", newline="\n") as f:
        f.write("// GENERATED by tools/gen_trades.py from tools/trades.json - don't edit by hand.\n")
        f.write("export const TRADES = " + json.dumps(cfg, indent=2) + ";\n")

    print(f"{len(keys)} trade tables for {len(cfg['professions'])} professions")


if __name__ == "__main__":
    main()
